### ISSUE TITLE
rotate counterclockwise and rotate clockwise, and document properties should appear on the toolbar at the top

### ISSUE THREAD

**Issue by 5953lc** [operasoftware/pdf.js#17]
RE: tools versus just putting the tools icons on the viewer bar at the top

I use rotate counterclockwise and rotate clockwise every few faxes (3rd or 4th on average) and I use the document properties information to go over file info - size, author, PDF version, etc.

first page and last page not very flexible, and are extraneous because you can just type the page number you want in the page box, whether it's first, last or somewhere in the middle.

**Comment by Rob--W** [comment]
Feature requests that are not specific to Opera suit better at mozilla's bug tracker (https://github.com/mozilla/pdf.js/issues), because AFAIK no-one at Opera Software actively contributes to PDF.js.

That having said, did you know that there are shortcuts to rotate the document? https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#wiki-faq-shortcuts

**Comment by 5953lc** [comment]
nope.  I am an idiot. I didn't think to look. (there was no help!)

:-)

Thanks Rob

**Comment by 5953lc** [comment]
thanks, I just think Opera updated to the new one.
