### ISSUE TITLE
What is the purpose of insertFakeXML?

### ISSUE THREAD

**Issue by Rob--W** [operasoftware/pdf.js#2]
I've audited the source of https://addons.opera.com/en/extensions/details/pdf-viewer, and noticed that it slightly differs from the source in this repository.

At the background page, `insertFakeXML` is called right after detecting that the captured request is a PDF file. This function inserts a content script, and dispatches a message to the tab.

In the content script, the message is handled as follows:

```
else if (message && message.type === 'showFakeXML' &&
  message.url === location.href) {
    window.stop();
    document.body.textContent = '';
  }
```

What is the purpose of this addition? The only functional difference from the original code is that the new code is also activated for PDF _downloads_ (triggered by PDF.js).

`pdfHandler.js` (the background script) looks like this at the moment:

```
insertFakeXML(details.tabId, details.url);
if (isPdfDownloadable(details)) { ..........cut..............
  return;
}
// Replace frame's content with the PDF viewer
// This approach maintains the friendly URL in the location bar
activatePDFJSForTab(details.tabId, details.url);
```

This change seems unnecessary to me, because `activatePDFJSForTab` does the same (+one thing more) as `insertFakeXML`. Did you have a specific reason for this change?

**Comment by miketaylr** [comment]
Hey @Rob--W. The motivations for this tweak are purely cosmetic. On OSX, we found you could still see the "flash of unhidden XML error page", or FOUXEP as everyone calls it for a split second when viewing a PDF. Which is strange, admittedly. This was (at least last week) also reproducible on Canary. 

`insertFakeXML` was basically a quick fix so we could release the extension. We'll have to take a closer look to see what the real issue is.

**Comment by Rob--W** [comment]
I think that the FOUXEP is unavoidable. For example, keep F5 pressed, and the FOUXEP will constanty be shown (because the viewer did not get a chance to load).

This method was used to maintain a "nice" URL in the omnibox, because Chromium 27 and earlier just show a blank space for extension URLs.

Chrome 28+ shows a long `chrome-extension://EXTENSION-ID-HERE/web/viewer.html?file=URL-ENCODED-URL-HERE`. Which option would you prefer, FOUXEP or that long URL?

**Comment by 5953lc** [comment]
I'm not sure why I'm getting this email about FOUXEP or insertFakeXML.

I'd prefer not seeing anything at all since
1) there's nothing to display
2) crappy web programming ? :)
3) the faster that PDF.js works the better as far as I'm concerned...

Thanks though for all the great work - it's lovely not having to load Adobe.
